name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      # Set to 'gnuarmemb' 'zephyr' or 'zephyr-full' (from fastest to
      # most compatible). ZMK Studio requires 'zephyr-full'.
      toolchain: zephyr
