name: Test Local Build Environment
on:
  workflow_dispatch:
  push:
    paths:
      - nix/**
      - flake.*
      - .github/workflows/test-build-env.yml

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04,     system: x86_64-linux }
          - { os: ubuntu-24.04-arm, system: aarch64-linux }
          - { os: macos-13,         system: x86_64-darwin }
          - { os: macos-15,         system: aarch64-darwin }

    name: ${{ matrix.system }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Set up build environment
        run: nix develop --command just init
      - name: Test build recipe
        run: nix develop --command just build planck
      - name: Test draw recipe
        run: nix develop --command just draw
